spring.application.name=to_do_list_final-project
api-endpoint=/to-do-list

spring.datasource.url=jdbc:mysql://localhost:3306/to-do-list_database
spring.datasource.username=root
spring.datasource.password=supersecreta
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080